import type { Metadata } from "next";
import { Inter} from "next/font/google";
import "./globals.css";
 // Ensure this is the correct module for Tanker

// Example: app/layout.tsx or pages/_app.tsx



const inter = Inter({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-inter',
  display: 'swap',
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://api.fontshare.com/v2/css?f[]=tanker@400,700,500,900,800&display=swap" rel="stylesheet"/>

      </head>
      <body className={`${inter.variable}`}>{children}</body>
    </html>
  );
}
